```yaml
version: '3.8'

services:
  server:
    container_name: server-1
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis-1
    image: redis:7-alpine
    networks:
      - app-network
    ports:
      - "6379:6379"  
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
```