# Build Stage
FROM node:23-slim AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .

RUN npm run build

RUN node --max-old-space-size=2048 ./node_modules/.bin/tsc

# Production stage
FROM node:23-slim
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json /app/package-lock.json ./
RUN npm install --production --no-optional && npm cache clean --force
EXPOSE 5000
CMD ["npm", "start"]
