# Build Stage
FROM node:23-slim AS builder
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy all source files
COPY . .

# Increase memory limit and build project
ENV NODE_OPTIONS=--max-old-space-size=2048
RUN npm run build


# Production Stage
FROM node:23-slim
WORKDIR /app

# Copy built files and node_modules from builder stage
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Expose port
EXPOSE 5000

# Start the server
CMD ["npm", "start"]
